name: Cross-Platform Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, arm64]
    runs-on: ${{ matrix.platform }}
    
    steps:
    - uses: actions/checkout@v4
    
    # 设置MySQL开发环境
    - name: Set up MySQL dev environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libmysqlclient-dev
        
    # 对于ARM64平台的特殊处理
    - name: Setup ARM64 toolchain (if needed)
      if: matrix.platform == 'arm64'
      run: |
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
        
    # 编译步骤
    - name: Compile for native architecture
      if: matrix.platform == 'ubuntu-latest'
      run: |
        make LIBDIR=$PWD
        
    # ARM64交叉编译
    - name: Cross-compile for ARM64
      if: matrix.platform == 'ubuntu-latest'
      run: |
        aarch64-linux-gnu-gcc -Wall -I/usr/include/mysql -I. -shared lib_mysqludf_sys.c \
          -o lib_mysqludf_sys-arm64.so
        
    # 在原生ARM64平台上编译
    - name: Native compile on ARM64
      if: matrix.platform == 'arm64'
      run: |
        make LIBDIR=$PWD
        mv lib_mysqludf_sys.so lib_mysqludf_sys-arm64-native.so
        
    # 打包制品
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: udf-binaries
        path: |
          lib_mysqludf_sys.so
          lib_mysqludf_sys-arm64.so
          lib_mysqludf_sys-arm64-native.so
