name: Build lib_mysqludf_sys for ARM/ARM64

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [arm, arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 设置QEMU模拟器用于跨架构编译
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.platform }}
      
      # 设置Docker构建x环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # 安装MySQL开发环境和编译工具链
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc make
          if [ "${{ matrix.platform }}" = "arm" ]; then
            sudo apt-get install -y gcc-arm-linux-gnueabihf libmysqlclient-dev:armhf
          else
            sudo apt-get install -y gcc-aarch64-linux-gnu libmysqlclient-dev:arm64
          fi
      
      # 编译项目
      - name: Compile lib_mysqludf_sys
        run: |
          if [ "${{ matrix.platform }}" = "arm" ]; then
            export CC=arm-linux-gnueabihf-gcc
          else
            export CC=aarch64-linux-gnu-gcc
          fi
          make LIBDIR=/usr/lib
      
      # 上传编译产物
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lib_mysqludf_sys-${{ matrix.platform }}
          path: lib_mysqludf_sys.so
