name: Build lib_mysqludf_sys for ARM/ARM64 with MariaDB

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [arm, arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 设置QEMU模拟器用于跨架构编译
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.platform }}
      
      # 设置Docker构建x环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # 安装MariaDB开发环境和编译工具链
      - name: Install MariaDB dependencies
        run: |
          sudo apt-get update
          
          # 安装MariaDB服务器和开发包
          sudo apt-get install -y mariadb-server libmariadb-dev-compat libmariadb-dev
          
          # 安装交叉编译工具链
          sudo apt-get install -y build-essential gcc make
          if [ "${{ matrix.platform }}" = "arm" ]; then
            sudo apt-get install -y gcc-arm-linux-gnueabihf
          else
            sudo apt-get install -y gcc-aarch64-linux-gnu
          fi
      
      # 修改源代码以兼容MariaDB
      - name: Modify source code for MariaDB
        run: |
          # 移除my_global.h引用
          sed -i 's/#include <my_global.h>//' lib_mysqludf_sys.c
          
          # 确保包含正确的MySQL头文件
          if ! grep -q "#include <mysql.h>" lib_mysqludf_sys.c; then
            sed -i '1i#include <mysql.h>' lib_mysqludf_sys.c
          fi
      
      # 编译项目
      - name: Compile lib_mysqludf_sys
        run: |
          if [ "${{ matrix.platform }}" = "arm" ]; then
            export CC=arm-linux-gnueabihf-gcc
          else
            export CC=aarch64-linux-gnu-gcc
          fi
          
          # 添加MariaDB头文件路径
          make LIBDIR=/usr/lib MYSQL_INCLUDE=/usr/include/mysql
      
      # 上传编译产物
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lib_mysqludf_sys-${{ matrix.platform }}
          path: lib_mysqludf_sys.so
