name: Cross-platform UDF Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        platform: [arm, arm64]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        # 安装交叉编译工具链
        if [ "${{ matrix.platform }}" = "arm" ]; then
          sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
        else
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
        fi
        # 安装MySQL开发包（使用MariaDB版本）
        sudo apt-get install -y libmariadb-dev-compat libmariadb-dev

    - name: Find MySQL headers
      run: |
        echo "MySQL headers location:"
        find /usr -name my_global.h -type f 2>/dev/null || echo "No my_global.h found"

    - name: Compile for ${{ matrix.platform }}
      run: |
        # 查找MySQL头文件路径
        MYSQL_INCLUDE=$(find /usr -name my_global.h -type f 2>/dev/null | head -1 | xargs dirname)
        if [ -z "$MYSQL_INCLUDE" ]; then
          echo "Error: my_global.h not found!"
          exit 1
        fi
        
        if [ "${{ matrix.platform }}" = "arm" ]; then
          CC=arm-linux-gnueabihf-gcc
          FLAGS="-march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard"
        else
          CC=aarch64-linux-gnu-gcc
          FLAGS="-march=armv8-a"
        fi
        
        echo "Compiling with MySQL headers from: $MYSQL_INCLUDE"
        $CC $FLAGS -DMYSQL_DYNAMIC_PLUGIN -fPIC -Wall \
          -I$MYSQL_INCLUDE \
          -I$(dirname $MYSQL_INCLUDE) \
          -shared lib_mysqludf_sys.c -o lib_mysqludf_sys_${{ matrix.platform }}.so

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lib_mysqludf_sys_${{ matrix.platform }}.so
        path: lib_mysqludf_sys_${{ matrix.platform }}.so
