name: Cross-platform UDF Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [arm, arm64]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install cross-compilation toolchain
      run: |
        sudo apt-get update
        if [ "${{ matrix.platform }}" = "arm" ]; then
          sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
        else
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
        fi

    - name: Compile for ${{ matrix.platform }}
      run: |
        if [ "${{ matrix.platform }}" = "arm" ]; then
          CC=arm-linux-gnueabihf-gcc
          TARGET=arm-linux-gnueabihf
          FLAGS="-march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard"
        else
          CC=aarch64-linux-gnu-gcc
          TARGET=aarch64-linux-gnu
          FLAGS="-march=armv8-a"
        fi
        
        $CC $FLAGS -DMYSQL_DYNAMIC_PLUGIN -fPIC -Wall -I/usr/include/mysql -shared lib_mysqludf_sys.c -o lib_mysqludf_sys_${{ matrix.platform }}.so

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lib_mysqludf_sys_${{ matrix.platform }}.so
        path: lib_mysqludf_sys_${{ matrix.platform }}.so
