name: MySQL UDF ARM64 Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up build environment
      run: |
        sudo apt-get update
        # 安装交叉编译工具和 MySQL 开发包
        sudo apt-get install -y \
          gcc-aarch64-linux-gnu \
          g++-aarch64-linux-gnu \
          libmysqlclient-dev \
          mysql-common \
          libmysqlclient21
        
    - name: Cross-compile for ARM64
      run: |
        # 自动检测 MySQL 头文件路径
        if command -v mysql_config >/dev/null; then
          MYSQL_INCLUDE=$(mysql_config --include | sed 's/-I//g' | awk '{print $1}')
        else
          MYSQL_INCLUDE="/usr/include/mysql"
        fi
        
        echo "Using MySQL include path: $MYSQL_INCLUDE"
        
        aarch64-linux-gnu-gcc -Wall \
          -I$MYSQL_INCLUDE \
          -I. \
          -shared -fPIC \
          lib_mysqludf_sys.c \
          -o lib_mysqludf_sys-arm64.so
        
        # 验证编译结果
        file lib_mysqludf_sys-arm64.so
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mysql-udf-arm64
        path: lib_mysqludf_sys-arm64.so
